apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-app
  namespace: argocd
spec:
  ignoreApplicationDifferences:
    - jsonPointers:
      - /spec/syncPolicy
  generators:
    - list:
        elements:
          - cluster: dev
            url: https://kubernetes.default.svc
          - cluster: staging
            url: https://kubernetes.default.svc
          - cluster: prod
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-nginx-app'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: https://github.com/ThorntonCloud/GitOps-Infra.git
        targetRevision: main
        path: nginx-app/overlays/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}'
