apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - namespace.yaml
  - ../../base

labels:
  - pairs:
      environment: dev
      tier: development

patches:
  - path: patches/deployment.yaml
    target:
      kind: Deployment
  - path: patches/service.yaml
    target:
      kind: Service

namePrefix: dev-

commonAnnotations:
  deployed-by: argocd
  environment: dev

images:
  - name: thorntoncloud/nginx-gitops
    newTag: latest

replicas:
  - name: nginx-app
    count: 1