apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applicationset-controller
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
   destination:
     name: ''
     namespace: argocd
     server: https://kubernetes.default.svc
   source:
     repoURL: https://github.com/ThorntonCloud/gitops-sample.git
     targetRevision: main
     path: argocd/appsets