apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applicationset-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ThorntonCloud/GitOps-Infra.git
    targetRevision: main
    path: argocd/appsets
  destination:
    name: ''
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true