apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - namespace.yaml
  - ../../base

labels:
  - pairs:
      environment: production
      tier: production

patches:
  - path: patches/deployment.yaml
    target:
      kind: Deployment
  - path: patches/service.yaml
    target:
      kind: Service
  - path: patches/configmap.yaml
    target:
      kind: ConfigMap

namePrefix: prod-

commonAnnotations:
  deployed-by: argocd
  environment: production
  critical: "true"

images:
  - name: thorntoncloud/nginx-gitops
    newTag: v1.0.0

replicas:
  - name: nginx-app
    count: 3